//////LOGIN ACTION TYPES
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGGING_IN = "LOGGING_IN";
export const LOGGING_OUT = "LOGGING_OUT";
export const LOG_OUT_SUCCESS = "LOG_OUT_SUCCESS";
export const GETTING_GENERAL_SETTINGS = "GETTING_GENERAL_SETTINGS";
export const GET_GENERAL_SETTINGS_SUCCESS = "GET_GENERAL_SETTINGS_SUCCESS";